import './globals.scss'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Game Keys',
    description: 'Generated by create next app',
}

export default function MyApp({ Component, pageProps }) {
    return <Component {...pageProps} />
}
